# Generated by Django 4.1.7 on 2023-03-30 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of advert')),
                ('description', models.TextField(verbose_name='Description of advert')),
                ('price', models.IntegerField(verbose_name='Price of advert')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date created')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.profile')),
            ],
        ),
    ]
