# Generated by Django 4.1.7 on 2023-04-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_advert_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advert/media')),
            ],
        ),
        migrations.RemoveField(
            model_name='advert',
            name='images',
        ),
        migrations.AddField(
            model_name='advert',
            name='images',
            field=models.ManyToManyField(to='advert.images'),
        ),
    ]
