# Generated by Django 4.1.7 on 2023-04-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('advert', '0003_images_remove_advert_images_advert_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='favourites',
            field=models.ManyToManyField(related_name='adverts', to='client.profile'),
        ),
    ]
