version: '3.8'

networks:
  aviato-network:
    external: true

services:
  aviato_backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/aviato/backend
    ports:
      - 8000:8000
    networks:
      - aviato-network
