# Generated by Django 4.1.7 on 2023-03-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of the vehicle model')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('plane', 'plane'), ('helicopter', 'helicopter'), ('glider', 'glider'), ('parts', 'parts')], max_length=50)),
                ('brand', models.CharField(max_length=50, verbose_name='Name of the vehicle brand')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Name of the vehicle model')),
                ('release_date', models.DateField(blank=True, verbose_name='Release date of advert')),
                ('power', models.IntegerField(blank=True, verbose_name='Power of engine')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the vehicle brand')),
                ('model', models.ManyToManyField(to='product.model', verbose_name='Possible models for brand')),
            ],
        ),
    ]
